import React from "react";
import Head from "next/head";
import {Footer, Navbar} from "./components";
import styles from "@/styles/Home.module.scss";
import {nunitoBold, ptSans} from "@/styles/fonts";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Gallery />
      <Footer />
    </div>
  );
};

export default Home;

const Hero = () => {
  return (
    <section className={`${styles.hero} ${styles.section}`}>
      <h1 className={`${nunitoBold.className}`}>HUBERT KLIMCZAK</h1>
      <div />
      <p className={`${ptSans.className}`}>
        Jestem grafikiem i ilustratorem z wielką pasją do sztuki i komputerowego
        tworzenia. Stawiam na ciągły rozwój moich umiejętności artystycznych,
        aby wspierać innowacyjność i doskonalić produkty. Lubię eksperymentować
        z nowymi technikami i trendami, co pomaga mi tworzyć unikalne dzieła
        sztuki. Moje prace zawsze dążą do doskonałości, a moja otwarta
        mentalność pozwala mi odkrywać nowe sposoby wyrażania kreatywności.
      </p>
    </section>
  );
};

const Gallery = () => {
  return (
    <section id="gallery" className={`${styles.gallery} ${styles.section}`}>
      <h2 className={`${nunitoBold.className}`}>GALLERY</h2>
      <a href="/visual-identification">1</a>
      <a href="/traditional-art">1</a>
      <a href="/digital-art">1</a>
    </section>
  );
};
